package io.configd.distribution.wire;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Hard-coded golden bytes for every edge-protocol fixture at
 * {@link EdgeFrameCodec#EDGE_WIRE_VERSION} v1 (CT-41; mirrors the Raft
 * {@code GoldenFixtures} pattern — hex constants in a Java map keyed by
 * {@code name.bin} so diffs are human-readable, not opaque binary files).
 *
 * <h2>Rebaseline rule (READ BEFORE editing any byte here)</h2>
 * These bytes are the pinned wire image of the edge protocol. They MUST NOT drift
 * silently. If {@code EdgeFrameCodecGoldenFixtureTest} fails, you have changed the
 * encoded bytes of a frame. Either revert the change, OR — if the change is an
 * intentional protocol evolution — <b>bump {@link EdgeFrameCodec#EDGE_WIRE_VERSION}</b>
 * and regenerate these constants by running {@code EdgeFrameGoldenBytesGenerator}
 * (its {@code main} prints fresh hex for every fixture). A bytes change without a
 * version bump is a wire-compat regression and the test fails by design (the same
 * guard the Raft {@code WireCompatGoldenBytesTest} enforces, kept on a separate codec
 * so the edge protocol never rides the Raft fixture gate — ADR-0037).
 *
 * <p>The 1 MiB at-cap snapshot-chunk fixture is too large to inline as hex; its golden
 * is its full-frame CRC32C in {@link #goldenCrc()} (the body is a deterministic fill,
 * regenerated by {@code EdgeFrameFixtures.oneMiBFill()}), so the at-cap path is still
 * byte-pinned.
 */
final class EdgeFrameGoldenBytes {

    private EdgeFrameGoldenBytes() {
    }

    static Map<String, byte[]> forVersion(int wireVersion) {
        if (wireVersion == 1) {
            return v1();
        }
        throw new IllegalArgumentException("No edge golden fixtures for wire version " + wireVersion);
    }

    private static Map<String, byte[]> v1() {
        Map<String, byte[]> m = new LinkedHashMap<>();
        m.put("subscribe_full_store.bin",          hex("00000029010101000000000000000000000000ffffffffffffffff00000006656467652d41b4ff5303"));
        m.put("subscribe_prefixes.bin",            hex("0000003801010000000002000000047376632f0000000364622f0000000000001000000000000000138800000006656467652d42cb106853"));
        m.put("subscribe_ok_tail.bin",             hex("000000130102000000000000303900429ac9fb"));
        m.put("subscribe_ok_snapshot_first.bin",   hex("000000130102000000000001093201c8b1a144"));
        m.put("notify_single_unsigned.bin",        hex("0000005901030000000100000000000000640000018bcfe56800000000000000006300000000000000640000001703000000010100077376632f63666700000004deadbeefffffffff00000000000000000000000088aeab64"));
        m.put("notify_batch_signed.bin",           hex("000000c301030000000200000000000000c80000018bcfe5686400000000000000c700000000000000c8000000110300000001010004612f6b31000000010100000010112233445566778899aabbccddeef00f000000000000000700000008010203040506070800000000000000c90000018bcfe568c800000000000000c800000000000000c90000000c0300000001020004612f6b3200000010112233445566778899aabbccddeef00f0000000000000008000000080102030405060708e39ada30"));
        m.put("notify_empty.bin",                  hex("0000000e0103000000007f154a94"));
        m.put("snapshot_begin.bin",                hex("0000001e010400000000000013880000000300000000002625a0f9e93808"));
        m.put("snapshot_chunk_small.bin",          hex("0000001201050000000010203040e8463923"));
        m.put("snapshot_end.bin",                  hex("0000001201060000000000001388fbf14ab3"));
        m.put("cursor_ack.bin",                    hex("00000012010700000000000010924094db35"));
        m.put("heartbeat.bin",                     hex("0000001a010800000000000023280000018bcfe569f4752fbdae"));
        m.put("error_bad_wire_version.bin",        hex("0000001f010901000000104241445f574952455f56455253494f4e3c7a20fc"));
        m.put("error_frame_too_large.bin",         hex("0000001e0109020000000f4652414d455f544f4f5f4c41524745dbb72b4f"));
        m.put("error_frame_corrupt.bin",           hex("0000001c0109030000000d4652414d455f434f525255505438853727"));
        m.put("error_auth_fail.bin",               hex("0000001801090400000009415554485f4641494c800eb68a"));
        m.put("error_bad_subscribe.bin",           hex("0000001c0109050000000d4241445f5355425343524942453adac624"));
        m.put("error_gap_unrecoverable.bin",       hex("00000020010906000000114741505f554e5245434f56455241424c45bda6e8de"));
        m.put("error_demoted_to_catchup.bin",      hex("000000210109070000001244454d4f5445445f544f5f43415443485550fb0c2626"));
        m.put("error_quarantined.bin",             hex("0000001a0109080000000b51554152414e54494e4544d3d1b649"));
        m.put("error_server_shutdown.bin",         hex("0000001e0109090000000f5345525645525f53485554444f574ebf3720a7"));
        m.put("error_protocol_violation.bin",      hex("0000002101090a0000001250524f544f434f4c5f56494f4c4154494f4e3844f60e"));
        return m;
    }

    /** Golden full-frame CRC32C for the 1 MiB at-cap snapshot chunk (too large to inline as hex). */
    static long goldenCrc() {
        return 0x4a0ac7f6L;
    }

    private static byte[] hex(String s) {
        byte[] out = new byte[s.length() / 2];
        for (int i = 0; i < out.length; i++) {
            out[i] = (byte) Integer.parseInt(s.substring(2 * i, 2 * i + 2), 16);
        }
        return out;
    }
}
