package io.configd.distribution.wire;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Hard-coded golden bytes for every edge-protocol fixture at
 * {@link EdgeFrameCodec#EDGE_WIRE_VERSION} v1 (mirrors the Raft
 * {@code GoldenFixtures} pattern - hex constants in a Java map keyed by
 * {@code name.bin} so diffs are human-readable, not opaque binary files).
 *
 * <h2>Rebaseline rule (READ BEFORE editing any byte here)</h2>
 * These bytes are the pinned wire image of the edge protocol. They MUST NOT drift
 * silently. If {@code EdgeFrameCodecGoldenFixtureTest} fails, you have changed the
 * encoded bytes of a frame. Either revert the change, or - if the change is an
 * intentional protocol evolution - <b>bump {@link EdgeFrameCodec#EDGE_WIRE_VERSION}</b>
 * and regenerate these constants by running {@code EdgeFrameGoldenBytesGenerator}
 * (its {@code main} prints fresh hex for every fixture). A bytes change without a
 * version bump is a wire-compat regression and the test fails by design (the same guard
 * the Raft {@code WireCompatGoldenBytesTest} enforces, kept on a separate codec
 * so the edge protocol never rides the Raft fixture gate).
 *
 * <p>The 1 MiB at-cap snapshot-chunk fixture is too large to inline as hex; its golden
 * is its full-frame CRC32C in {@link #goldenCrc()} (the body is a deterministic fill,
 * regenerated by {@code EdgeFrameFixtures.oneMiBFill()}), so the at-cap path is still
 * byte-pinned.
 *
 * <p><b>One exception to the rebaseline rule.</b> The SUBSCRIBE (0x01/0x03) and watch-cursor
 * (0x02 WATCH_CREATE / WATCH_PROGRESS / WATCH_CANCELED oldest) images were once redefined in
 * place, to prepend the {@code topologyEpoch:u64} and add the {@code STALE_TOPOLOGY(12)}
 * ERROR_CLOSE - a ratified clean break, done WITHOUT bumping
 * {@link EdgeFrameCodec#EDGE_WIRE_VERSION} because watches/edge had shipped no wire contract
 * yet. That is the one sanctioned exception to the no-drift rule above; every other drift is a
 * regression.
 */
public final class EdgeFrameGoldenBytes {

    private EdgeFrameGoldenBytes() {
    }

    /** The pinned golden frames for {@code wireVersion} (1..4), keyed by fixture name. Reused by the
     * conformance suite (via this module's test-jar) as the single-source-of-truth wire oracle. */
    public static Map<String, byte[]> forVersion(int wireVersion) {
        if (wireVersion == 1) {
            return v1();
        }
        if (wireVersion == 2) {
            return v2();
        }
        if (wireVersion == 3) {
            return v3();
        }
        if (wireVersion == 4) {
            return v4();
        }
        throw new IllegalArgumentException("No edge golden fixtures for wire version " + wireVersion);
    }

    private static Map<String, byte[]> v1() {
        Map<String, byte[]> m = new LinkedHashMap<>();
        m.put("subscribe_full_store.bin",          hex("000000310101010000000000000000000000010000000000000000ffffffffffffffff00000006656467652d411f55c56f"));
        m.put("subscribe_prefixes.bin",            hex("0000004001010000000002000000047376632f0000000364622f00000000000000010000000000001000000000000000138800000006656467652d42c98a5f52"));
        m.put("subscribe_ok_tail.bin",             hex("000000130102000000000000303900429ac9fb"));
        m.put("subscribe_ok_snapshot_first.bin",   hex("000000130102000000000001093201c8b1a144"));
        m.put("notify_single_unsigned.bin",        hex("0000005901030000000100000000000000640000018bcfe56800000000000000006300000000000000640000001703000000010100077376632f63666700000004deadbeefffffffff00000000000000000000000088aeab64"));
        m.put("notify_batch_signed.bin",           hex("000000c301030000000200000000000000c80000018bcfe5686400000000000000c700000000000000c8000000110300000001010004612f6b31000000010100000010112233445566778899aabbccddeef00f000000000000000700000008010203040506070800000000000000c90000018bcfe568c800000000000000c800000000000000c90000000c0300000001020004612f6b3200000010112233445566778899aabbccddeef00f0000000000000008000000080102030405060708e39ada30"));
        m.put("notify_empty.bin",                  hex("0000000e0103000000007f154a94"));
        m.put("snapshot_begin.bin",                hex("0000001e010400000000000013880000000300000000002625a0f9e93808"));
        m.put("snapshot_chunk_small.bin",          hex("0000001201050000000010203040e8463923"));
        m.put("snapshot_end.bin",                  hex("0000001201060000000000001388fbf14ab3"));
        m.put("cursor_ack.bin",                    hex("00000012010700000000000010924094db35"));
        m.put("heartbeat.bin",                     hex("0000001a010800000000000023280000018bcfe569f4752fbdae"));
        m.put("error_bad_wire_version.bin",        hex("0000001f010901000000104241445f574952455f56455253494f4e3c7a20fc"));
        m.put("error_frame_too_large.bin",         hex("0000001e0109020000000f4652414d455f544f4f5f4c41524745dbb72b4f"));
        m.put("error_frame_corrupt.bin",           hex("0000001c0109030000000d4652414d455f434f525255505438853727"));
        m.put("error_auth_fail.bin",               hex("0000001801090400000009415554485f4641494c800eb68a"));
        m.put("error_bad_subscribe.bin",           hex("0000001c0109050000000d4241445f5355425343524942453adac624"));
        m.put("error_gap_unrecoverable.bin",       hex("00000020010906000000114741505f554e5245434f56455241424c45bda6e8de"));
        m.put("error_demoted_to_catchup.bin",      hex("000000210109070000001244454d4f5445445f544f5f43415443485550fb0c2626"));
        m.put("error_quarantined.bin",             hex("0000001a0109080000000b51554152414e54494e4544d3d1b649"));
        m.put("error_server_shutdown.bin",         hex("0000001e0109090000000f5345525645525f53485554444f574ebf3720a7"));
        m.put("error_protocol_violation.bin",      hex("0000002101090a0000001250524f544f434f4c5f56494f4c4154494f4e3844f60e"));
        return m;
    }

    /**
     * Hard-coded golden bytes for the 0x02 ({@link EdgeFrameCodec#EDGE_WIRE_VERSION_V2})
     * fixtures (the watch frames + a reused NOTIFY + the NOT_AUTHORIZED ERROR_CLOSE).
     * Generated by {@code EdgeFrameGoldenBytesGenerator} and independently CRC-verified. The
     * same rebaseline rule applies: a drift here is a 0x02 wire-format change.
     *
     * <p>{@code notify_reused.bin} is byte-identical to the v1 {@code notify_single_unsigned.bin}
     * except the version byte (offset 4: {@code 01} to {@code 02}) and the trailing CRC - the
     * design-A "only the version byte differs" property, asserted by
     * {@code EdgeFrameCodecV2GoldenFixtureTest}.
     */
    private static Map<String, byte[]> v2() {
        Map<String, byte[]> m = new LinkedHashMap<>();
        m.put("watch_create.bin",                  hex("00000038020a00000000000000070200000000077376632f63666700000000000000010000000100000000000000000000002a05afc1ae1d"));
        m.put("watch_create_fromnow.bin",          hex("00000029020a00000000000000080001000000047376632f000000000000000100000000001c9fd1a5"));
        m.put("watch_create_full.bin",             hex("00000025020a00000000000000090202000000000000000000000001000000000131769d76"));
        m.put("watch_cancel.bin",                  hex("00000012020b0000000000000007e6a20805"));
        m.put("watch_created.bin",                 hex("00000030020c000000000000000700000002000000000000000000000064000000000100000000000000c80125212c1f"));
        m.put("watch_event.bin",                   hex("00000056020d00000000000000070000000000000000000000650000018bcfe568000000000300000004612f6b310000000002dead00000007612f656d707479000000000000000004612f6b3201ffffffff0ea7e9d1"));
        m.put("watch_event_batch.bin",             hex("0000007d020d00000000000000070000000000000000000000fa0000018bcfe56cd200000005000000057376632f610000000003010203000000057376632f620000000002cafe000000097376632f656d7074790000000000000000087376632f676f6e6501ffffffff000000057376632f630000000001ffa817d9d8"));
        m.put("watch_progress.bin",                hex("0000003e020e00000000000000070000000000000001000000020000000000000000000000650000000100000000000000cd0000018bcfe569f4a237dcb2"));
        m.put("watch_canceled_gap.bin",            hex("00000033020f0000000000000007060100000000000000010000000100000000000000000000003200000003676170682157e9"));
        m.put("watch_canceled_not_authorized.bin", hex("00000018020f000000000000000b0b0000000000e64af1cf"));
        m.put("watch_snapshot_begin.bin",          hex("0000002a021000000000000000070000000100000000000000c80000000200000000000010004270eb2f"));
        m.put("watch_snapshot_chunk.bin",          hex("0000001e0211000000000000000700000001000000001020304007109243"));
        m.put("watch_snapshot_end.bin",            hex("0000001e021200000000000000070000000100000000000000c8504f2f69"));
        m.put("notify_reused.bin",                 hex("0000005902030000000100000000000000640000018bcfe56800000000000000006300000000000000640000001703000000010100077376632f63666700000004deadbeefffffffff0000000000000000000000007fcf3b79"));
        m.put("error_not_authorized.bin",          hex("0000001d02090b0000000e4e4f545f415554484f52495a45448c0f2e2c"));
        m.put("error_stale_topology.bin",          hex("0000001d02090c0000000e5354414c455f544f504f4c4f4759329b1d72"));
        m.put("error_credential_expired.bin",      hex("0000002102090d0000001243524544454e5449414c5f4558504952454466be04e5"));
        return m;
    }

    /**
     * Hard-coded golden bytes for the 0x03 ({@link EdgeFrameCodec#EDGE_WIRE_VERSION_V3})
     * fixtures: the filtered-fan-out SUBSCRIBE / SUBSCRIBE_OK, which carry an extra trailing
     * opt-in / confirm byte over their 0x01 forms (ADR-0045). Generated by
     * {@code EdgeFrameGoldenBytesGenerator} and independently CRC-verified. The same rebaseline
     * rule applies: a drift here is a 0x03 wire-format change. The 0x01/0x02 golden images are
     * untouched (purely additive, like 0x02 over 0x01).
     */
    private static Map<String, byte[]> v3() {
        Map<String, byte[]> m = new LinkedHashMap<>();
        m.put("subscribe_full_store.bin",           hex("000000320301010000000000000000000000010000000000000000ffffffffffffffff00000006656467652d41003cf5d841"));
        m.put("subscribe_prefixes_filtered.bin",    hex("0000004103010000000002000000047376632f0000000364622f00000000000000010000000000001000000000000000138800000006656467652d420157e6d413"));
        m.put("subscribe_ok_filtered.bin",          hex("000000140302000000000000303900013a6e8f8e"));
        m.put("subscribe_ok_unfiltered.bin",        hex("0000001403020000000000010932010024896908"));
        return m;
    }

    /**
     * Hard-coded golden bytes for the 0x04 ({@link EdgeFrameCodec#EDGE_WIRE_VERSION_V4}) auth-phase
     * fixtures: {@link EdgeFrame.Auth} (bearer + basic) and {@link EdgeFrame.RefreshAuth}. Generated by
     * {@code EdgeFrameGoldenBytesGenerator} and independently CRC-verified. The same rebaseline rule
     * applies: a drift here is a 0x04 wire-format change. The 0x01/0x02/0x03 golden images are untouched
     * (purely additive) - the AUTH frame is orthogonal to the business/watch/filter versions.
     */
    private static Map<String, byte[]> v4() {
        Map<String, byte[]> m = new LinkedHashMap<>();
        m.put("auth_bearer.bin",          hex("0000001e0413010000000f676f6c64656e2d746f6b656e2d3432d1a2e2f1"));
        m.put("auth_basic.bin",           hex("0000001e04130200000005616c69636500000006733363726574c4c94315"));
        m.put("refresh_auth_bearer.bin",  hex("0000001f04140100000010726566726573682d746f6b656e2d3939739ee8e1"));
        return m;
    }

    /** Golden full-frame CRC32C for the 1 MiB at-cap snapshot chunk (too large to inline as hex). */
    static long goldenCrc() {
        return 0x4a0ac7f6L;
    }

    /** Golden full-frame CRC32C for the 1 MiB at-cap WATCH_SNAPSHOT_CHUNK (v2; too large to inline). */
    static long goldenCrcV2() {
        return 0x9a7567e1L;
    }

    private static byte[] hex(String s) {
        byte[] out = new byte[s.length() / 2];
        for (int i = 0; i < out.length; i++) {
            out[i] = (byte) Integer.parseInt(s.substring(2 * i, 2 * i + 2), 16);
        }
        return out;
    }
}
